### ISSUE TITLE
Romanji

### ISSUE THREAD

**Issue by V1rusFalcon** [Mikibot/Miki.Anilist#3]
why didn't you put the Romanji's title variable?

**Comment by velddev** [comment]
Use the `NativeTitle` variable in `IMedia` to get the romaji title

**Comment by V1rusFalcon** [comment]
Nativetitle does not report romanji but kanji example 僕のヒーローアカデミア instead boku no hero academia

**Comment by velddev** [comment]
Ah, I see. I think it's called `EnglishTitle` then. Sorry, I mixed up terms there.

**Comment by V1rusFalcon** [comment]
Wait, I think you don't understand. I need the romanji and through the lib I only get the title in english and kanji. I need to get "Boku No Hero Academia" instead of "僕のヒーローアカデミア" or "My hero academia".

**Comment by velddev** [comment]
Check in c.a. 20 minutes for the nuget push.

**Comment by V1rusFalcon** [comment]
i don't know why but the romaji title is always empty

**Comment by V1rusFalcon** [comment]
UPDATE: is always empty when is returned from searchmediaasync

**Comment by velddev** [comment]
🤔

**Comment by velddev** [comment]
Ah yes, I noticed something I've missed; the search query did not by default request the romaji version.

**Comment by velddev** [comment]
This has been done I think :)
